server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_database_dev?createDatabaseIfNotExist=true
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    servlet:
      path: /api/v1/order
